# TODO: Plot results of diversity analysis using Hill numbers
# generated by function iNEXT in package iNEXT as described in
# Chao et al. Ecol. Monogr. (2014). Similar to function ggiNEXT
# but more easely customizable.
###############################################################################

plot.iNEXT.rar <- function(data, plot.type=c('abundance', 'coverage'), 
		do.facet=F, nrows=NULL, ...) {
	
#	require(ggplot2)
#	require(ggthemes)
#	require(gridExtra)
#	require(scales)
#	require(RColorBrewer)
	
	data <- data$iNextEst
	plot.dat <- NULL
	plot.ref.point <- NULL
	plot.extr.line <- NULL
	
	for (i in 1:length(data)) {
		x <- data[[i]]
		n <- length(x$m)
		ref.point <- match('observed',x$method)
		extr.line <- match('extrapolated',x$method)
		
		if(is.null(nrows)) {
			nrows <- floor(length(data)/2)
		}
		
		if(plot.type=='abundance') {
			dep.var <- x$qD
			LCL <- x$qD.LCL
			UCL <- x$qD.UCL
			mxx <- 'Number of individuals'
			myy <- 'Number of species'
		}
		
		if(plot.type=='coverage') {
			dep.var <- x$SC
			LCL <- x$SC.LCL
			UCL <- x$SC.UCL
			mxx <- 'Number of sampling units'
			myy <- 'Sample coverage'
		}
		
		if(!is.na(ref.point)) {
			ref.point.dat=data.frame(data.name=names(data)[i], x=x$t[ref.point], y=dep.var[ref.point])
		}
		
		else {
			ref.point.dat <- data.frame(data.name=names(data)[i], x=NA, y=NA)
		}
		
		if(!is.na(extr.line)) {
			
			n1 <- as.numeric(extr.line)
			dat <- data.frame(data.name=rep(names(data)[i], n1), Nind=x$t[1:n1],
					diversity=dep.var[1:n1], lci=LCL[1:n1], uci=UCL[1:n1])
			extr.line.dat <- data.frame(data.name=rep(names(data)[i], length(n1:n)), Nind=x$t[n1:n],
					diversity=dep.var[n1:n], lci=LCL[n1:n], uci=UCL[n1:n])
		}
		
		else {
			dat <- data.frame(data.name=rep(names(data)[i], n), Nind=x$t,
					diversity=dep.var, lci=LCL, uci=UCL)
			extr.line.dat <- data.frame(data.name=rep(names(data)[i], n), Nind=rep(NA, n),
					diversity=rep(NA, n), lci=rep(NA, n), uci=rep(NA,n))
		}
		
		plot.dat <- rbind(plot.dat, dat)
		plot.ref.point <- rbind(plot.ref.point, ref.point.dat)
		plot.extr.line <- rbind(plot.extr.line, extr.line.dat)
	}
	
	if(do.facet) {
		p <- ggplot(data=plot.dat, aes(x=Nind, y=diversity))
		p+geom_path(aes(colour=data.name), alpha=0.9, size=1)+
				geom_ribbon(aes(x=Nind, ymin=lci, ymax=uci, colour=NA, fill=data.name), alpha=0.3)+
				geom_path(data=plot.extr.line, aes(x=Nind, y=diversity, colour=data.name),
						netype='dashed', alpha=0.9, size=1)+
				geom_ribbon(data=plot.extr.line, aes(x=Nind, ymin=lci, ymax=uci, colour=NA, fill=data.name), alpha=0.3)+
				geom_point(data=plot.ref.point, aes(x=x, y=y, col=data.name,
						shape=data.name), size=3)+
				scale_fill_fish_d(option = "Cirrhilabrus_solorensis", begin=0.05, end=0.95, direction=1) +
				scale_color_fish_d(option = "Cirrhilabrus_solorensis", begin=0.05, end=0.95, direction=1) +
				facet_wrap(~data.name, scales='free', nrow=nrows)+
				theme_bw()+
				labs(x=mxx, y=myy) +
				sjPlot::theme_sjplot(base_family="arial")+
				set_theme(base=theme_bw(),
						legend.pos="none")+
				theme(text=element_text(size=10))
#				theme(legend.position="none")+
#				theme(axis.title.y=element_text(size=14))+
#				theme(panel.grid.major=element_line(colour=NA), panel.grid.minor=element_line(colour=NA))+
				theme(panel.background = element_blank(), panel.border=element_rect(colour="black"))
	}
	
	else {
		
		np <- length(data)
		p <- ggplot(data=plot.dat, aes(x=Nind, y=diversity))
		
		p+geom_path(aes(colour=data.name), alpha=0.9, size=1)+
				geom_ribbon(aes(x=Nind, ymin=lci, ymax=uci, colour=NA, fill=data.name), alpha=0.3)+
				geom_path(data=plot.extr.line, aes(x=Nind, y=diversity, colour=data.name),
						linetype='dashed', alpha=0.9, size=1)+
				geom_ribbon(data=plot.extr.line, aes(x=Nind, ymin=lci, ymax=uci, colour=NA, fill=data.name), alpha=0.3)+
				geom_point(data=plot.ref.point, aes(x=x, y=y, col=data.name,
						shape=data.name), size=3)+
				scale_fill_fish_d(option = "Cirrhilabrus_solorensis", begin=0.05, end=0.95, direction=1) +
				scale_color_fish_d(option = "Cirrhilabrus_solorensis", begin=0.05, end=0.95, direction=1) +
				theme_bw()+
				labs(x=mxx, y=myy)+	
				theme_bw()+
				sjPlot::theme_sjplot(base_family="arial")+	
				set_theme(base=theme_bw(),
						legend.pos="none")+
				theme(text=element_text(size=10))
#				theme(
#						legend.position="none",
#						text=element_text(size=10),
#						#axis.title.y=element_text(size=12),
#						panel.grid.major=element_line(colour=NA),
#						panel.grid.minor=element_line(colour=NA),
#						panel.border=element_rect(colour="black")
#				)
		
	}
}

